version: "2"
services:
  millionaire:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80"
    volumes:
      - /srv/maciejbadziak/millionaire-show/millionaire-ee3574c78394.json:/usr/share/millionaire-ee3574c78394.json
    networks:
      piotrzur_net:
        aliases:
          - millionaire
networks:
  piotrzur_net:
    external: true
